---

- hosts: all
  tasks:

          - file:
              path: $HOME/.config/nvim
              state: directory

          - file:
              src: $HOME/dotfiles/files/vimrc
              dest: $HOME/.config/nvim/init.vim
              state: link

          - file:
              src: $HOME/dotfiles/files/coc-settings.json
              dest: $HOME/.config/nvim/coc-settings.json
              state: link
